# Generated by Django 5.0.6 on 2024-07-01 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Vinilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('autor', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.categoria')),
            ],
        ),
    ]
