# Generated by Django 5.0.6 on 2024-07-01 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_vinilo_portada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorC', models.IntegerField()),
                ('portadaC', models.ImageField(null=True, upload_to='clasicas')),
                ('autorC', models.CharField(max_length=30)),
                ('nombreC', models.CharField(max_length=30)),
                ('CategoriaC', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Jazz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorJ', models.IntegerField()),
                ('portadaJ', models.ImageField(null=True, upload_to='jazzs')),
                ('autorJ', models.CharField(max_length=30)),
                ('nombreJ', models.CharField(max_length=30)),
                ('CategoriaJ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Rock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorR', models.IntegerField()),
                ('portadaR', models.ImageField(null=True, upload_to='rocks')),
                ('autorR', models.CharField(max_length=30)),
                ('nombreR', models.CharField(max_length=30)),
                ('CategoriaR', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.categoria')),
            ],
        ),
    ]
